export const mergeSortJavaLines = [
  { id: 'CALL', text: 'public void mergeSort(int esquerda, int direita) {' },
  { id: 'CHECK_BASE', text: '    if (esquerda >= direita) {' },
  { id: 'BASE_CASE', text: '        return;' },
  { id: 'END_CHECK_BASE', text: '    }' },
  { id: 'CALC_MID', text: '    int meio = (esquerda + direita) / 2;' },
  { id: 'RECURSE_LEFT', text: '    mergeSort(esquerda, meio);' },
  { id: 'RECURSE_RIGHT', text: '    mergeSort(meio + 1, direita);' },
  { id: 'CALL_MERGE', text: '    merge(esquerda, meio, direita);' },
  { id: 'END_FUNC_SORT', text: '}' },
  { id: 'BLANK_1', text: '' },
  { id: 'MERGE_SIGNATURE', text: 'public void merge(int esquerda, int meio, int direita) {' },
  { id: 'COPY_LEFT', text: '    int[] L = Arrays.copyOfRange(vetor, esquerda, meio + 1);' },
  { id: 'COPY_RIGHT', text: '    int[] R = Arrays.copyOfRange(vetor, meio + 1, direita + 1);' },
  { id: 'INIT_POINTERS', text: '    int i = 0, j = 0, k = esquerda;' },
  { id: 'WHILE_MAIN', text: '    while (i < L.length && j < R.length) {' },
  { id: 'COMPARE', text: '        if (L[i] <= R[j]) {' },
  { id: 'TAKE_LEFT', text: '            vetor[k] = L[i]; i++;' },
  { id: 'ELSE_COMPARE', text: '        } else {' },
  { id: 'TAKE_RIGHT', text: '            vetor[k] = R[j]; j++;' },
  { id: 'END_COMPARE', text: '        }' },
  { id: 'INCREMENT_K', text: '        k++;' },
  { id: 'END_WHILE_MAIN', text: '    }' },
  { id: 'WHILE_LEFT_REMAINING', text: '    while (i < L.length) {' },
  { id: 'COPY_REMAINING_LEFT', text: '        vetor[k] = L[i]; i++; k++;' },
  { id: 'END_WHILE_LEFT', text: '    }' },
  { id: 'WHILE_RIGHT_REMAINING', text: '    while (j < R.length) {' },
  { id: 'COPY_REMAINING_RIGHT', text: '        vetor[k] = R[j]; j++; k++;' },
  { id: 'END_WHILE_RIGHT', text: '    }' },
  { id: 'END_FUNC_MERGE', text: '}' }
];
