export const mergeSortPseudocodigoLines = [
  { id: 'CALL', text: 'MERGE_SORT(Vetor, esquerda, direita)' },
  { id: 'CHECK_BASE', text: '    se esquerda >= direita' },
  { id: 'BASE_CASE', text: '        retorna' },
  { id: 'CALC_MID', text: '    meio = (esquerda + direita) / 2' },
  { id: 'RECURSE_LEFT', text: '    MERGE_SORT(Vetor, esquerda, meio)' },
  { id: 'RECURSE_RIGHT', text: '    MERGE_SORT(Vetor, meio+1, direita)' },
  { id: 'CALL_MERGE', text: '    MERGE(Vetor, esquerda, meio, direita)' },
  { id: 'BLANK_1', text: '' },
  { id: 'MERGE_SIGNATURE', text: 'MERGE(Vetor, esquerda, meio, direita)' },
  { id: 'COPY_LEFT', text: '    L = Vetor[esquerda..meio]' },
  { id: 'COPY_RIGHT', text: '    R = Vetor[meio+1..direita]' },
  { id: 'INIT_POINTERS', text: '    i = 0, j = 0, k = esquerda' },
  { id: 'WHILE_MAIN', text: '    enquanto i < tamanho(L) e j < tamanho(R)' },
  { id: 'COMPARE', text: '        se L[i] <= R[j]' },
  { id: 'TAKE_LEFT', text: '            Vetor[k] = L[i]; i = i + 1' },
  { id: 'ELSE_COMPARE', text: '        senão' },
  { id: 'TAKE_RIGHT', text: '            Vetor[k] = R[j]; j = j + 1' },
  { id: 'INCREMENT_K', text: '        k = k + 1' },
  { id: 'WHILE_LEFT_REMAINING', text: '    enquanto i < tamanho(L)' },
  { id: 'COPY_REMAINING_LEFT', text: '        Vetor[k] = L[i]; i = i + 1; k = k + 1' },
  { id: 'WHILE_RIGHT_REMAINING', text: '    enquanto j < tamanho(R)' },
  { id: 'COPY_REMAINING_RIGHT', text: '        Vetor[k] = R[j]; j = j + 1; k = k + 1' }
];
