export const mergeSortPythonLines = [
  { id: 'CALL', text: 'def merge_sort(vetor, esquerda, direita):' },
  { id: 'CHECK_BASE', text: '    if esquerda >= direita:' },
  { id: 'BASE_CASE', text: '        return' },
  { id: 'CALC_MID', text: '    meio = (esquerda + direita) // 2' },
  { id: 'RECURSE_LEFT', text: '    merge_sort(vetor, esquerda, meio)' },
  { id: 'RECURSE_RIGHT', text: '    merge_sort(vetor, meio + 1, direita)' },
  { id: 'CALL_MERGE', text: '    merge(vetor, esquerda, meio, direita)' },
  { id: 'BLANK_1', text: '' },
  { id: 'MERGE_SIGNATURE', text: 'def merge(vetor, esquerda, meio, direita):' },
  { id: 'COPY_LEFT', text: '    L = vetor[esquerda:meio + 1]' },
  { id: 'COPY_RIGHT', text: '    R = vetor[meio + 1:direita + 1]' },
  { id: 'INIT_POINTERS', text: '    i = j = 0; k = esquerda' },
  { id: 'WHILE_MAIN', text: '    while i < len(L) and j < len(R):' },
  { id: 'COMPARE', text: '        if L[i] <= R[j]:' },
  { id: 'TAKE_LEFT', text: '            vetor[k] = L[i]; i += 1' },
  { id: 'ELSE_COMPARE', text: '        else:' },
  { id: 'TAKE_RIGHT', text: '            vetor[k] = R[j]; j += 1' },
  { id: 'INCREMENT_K', text: '        k += 1' },
  { id: 'WHILE_LEFT_REMAINING', text: '    while i < len(L):' },
  { id: 'COPY_REMAINING_LEFT', text: '        vetor[k] = L[i]; i += 1; k += 1' },
  { id: 'WHILE_RIGHT_REMAINING', text: '    while j < len(R):' },
  { id: 'COPY_REMAINING_RIGHT', text: '        vetor[k] = R[j]; j += 1; k += 1' }
];
